
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # naming the deployment


spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 service

  # Lets create a replica set of this with 2 instance/pod
  replicas: 2

  # template to use its labal for K8 service to launch in browser
  template:
    metadata:
      labels:
        app: nginx # This label connects to the service or any other

    # Lets define the container spec
    spec:
      containers:
      - name: nginx
        image: ahskhan/eng89automatednginx:latest # name of image pulls from dockerhub
        ports:
        - containerPort: 80

