# Create a diagram for node deployment and services 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 3
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: sremichael/sre_node_app:v3
        ports:
          - containerPort: 3000
        env:
          - name: DB_HOST
            value: mongodb://mongo:27017/posts
