apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
    name: sparta-node-app-deploy
    namespace: default

spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: node 
  targetCPUUtilizationPercentage: 50


  # K8
  # 
  # 
  #